[package]
name = "rust-vips"
version = "0.1.0"
authors = ["iavian"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
num_cpus = "1.13.0"
tokio = { version = "0.3.6", features = ["full"] }
